add argocd to sandbox job (SRE-59)
edx/jenkins-job-dsl pull request #1001
Opened 2020-06-05 06:52 UTC by nadeemshahzad

2020-06-05 12:43 UTC, adzuci commented on devops/jobs/CreateSandbox.groovy
> +                booleanParam("argocd",false,"This will install the ArgoCD in minikube in the sandbox")
If you want to you can remove "the" in front of "ArgoCD"

2021-03-18 20:26 UTC, adzuci requested changes
I think some of this may not be needed.

2021-03-18 20:26 UTC, adzuci commented on devops/jobs/CreateSandbox.groovy
> +                git {
@coryleeio pointed out that `configuration-internal` above is actually `edx-internal` so we shouldn't be checking it out twice.

Cory:
```
I also think that configuration-internal and configuration-secure, might actually be edx-internal and
edx-secure at a different level of abstraction and that adding edx-internal there may not be necessary, 
you have to remember that code is in configuration so it’s open source so relying on edx-internal directly 
isn’t appropriate
```

@nadeemshahzad could your logic point at the `configuration-internal` folder instead?

2021-03-26 12:13 UTC, nadeemshahzad commented
Closing as we don't want to install ArgoCD inside minikube on Sandox.

2021-03-26 13:17 UTC, adzuci commented on devops/jobs/CreateSandbox.groovy
> +                git {
@coryleeio I had misunderstood this and thought that `configuration-internal` was `edx-internal`, but it is in fact https://github.com/edx/sandbox-internal so we either need to:

1: Copy the four argocd django application folders out of edx-internal and into sandbox-internal.
2: Clone edx-internal onto the box.

2021-03-26 13:20 UTC, adzuci commented on devops/jobs/CreateSandbox.groovy
> +                git {
@nadeemshahzad would like to try #1 first since there is less of a risk of leaking remote config data.

2021-04-01 13:20 UTC, adzuci approved these changes
:shipit:

2021-04-01 23:24 UTC, adzuci commented on devops/jobs/CreateSandbox.groovy
> +                git {
That sounds good to me.

2021-04-02 02:34 UTC, merged