feat:re-run logic, test more than once incase of failure
edx/jenkins-job-dsl pull request #1352
Opened 2021-03-31 11:25 UTC by jazibhumayun

2021-03-31 11:44 UTC, jazibhumayun commented on dataeng/resources/warehouse-transforms-dbt.sh
> +# NO_OF_TRIES is currently set to '2' which will execute dbt test '2' times and can be increase as per the need.
re-run logic below

2021-03-31 12:06 UTC, macdiesel commented on dataeng/resources/warehouse-transforms-dbt.sh
> +#!/usr/bin/env bash
Lets add -with-retry to the name of the script.

2021-03-31 12:06 UTC, macdiesel commented on dataeng/resources/warehouse-transforms-dbt.sh
> +NO_OF_TRIES=2
Lets set this to 3 to start.

2021-03-31 12:07 UTC, macdiesel requested changes
Just a few requests.

2021-04-01 12:30 UTC, jazibhumayun commented
Created a new PR #1353 that is using ci_script to re-run flaky tests

2021-04-01 12:30 UTC, jazibhumayun commented
This PR will be closed and no longer will be needed.

2021-04-05 13:11 UTC, closed without merging