chore: Enable ORA Grading MFE for sandboxes
edx/jenkins-job-dsl pull request #1483
Opened 2021-12-20 15:42 UTC by jnlapierre

chore: Enable ORA Grading MFE for sandboxes, configuration updates.

2021-12-20 20:00 UTC, matthugs requested changes

2021-12-20 20:00 UTC, matthugs commented on devops/jobs/CreateSandbox.groovy
> +                stringParam("ora-grading_version","master","The repository version of the frontend-app-ora-grading")
This sets up `ora-grading_version` as an environment variable. Hyphens aren't super kosher in that context; I think many implementations would work, but stylistically we really should use only alphnumeric and underscores here.

2021-12-20 22:11 UTC, matthugs approved these changes

2021-12-23 14:17 UTC, adzuci approved these changes

2022-01-04 21:13 UTC, merged