feat: dbt monte carlo integration
edx/jenkins-job-dsl pull request #1563
Opened 2022-05-11 18:40 UTC by Hamza442

2022-05-12 17:04 UTC, AbdouSeck approved these changes

2022-05-12 21:00 UTC, pwnage101 requested changes

2022-05-12 21:00 UTC, pwnage101 commented on dataeng/resources/warehouse-transforms.sh
> +rm -rf ${WORKSPACE}/vault-config
These lines can be removed once you stop writing a vault token to disk

2022-05-13 05:58 UTC, Hamza442 commented on dataeng/resources/warehouse-transforms.sh
> +export VAULT_TOKEN="$(cat ${WORKSPACE}/vault-config/vault-token)"
If we directly write it into the VAULT_TOKEN environment variable then the problem of race condition remains as it is. First we went with this approach but this didn't work. It seems like when we directly write into the environment variable each job might be accessing the same variable.

2022-05-13 06:10 UTC, Hamza442 commented on dataeng/jobs/analytics/WarehouseTransforms.groovy
> +                    usernamePassword('ANALYTICS_VAULT_ROLE_ID', 'ANALYTICS_VAULT_SECRET_ID', 'analytics-vault');
Updated

2022-05-13 06:11 UTC, Hamza442 commented on dataeng/jobs/analytics/WarehouseTransforms.groovy
> +                    env('REMOTE_CONFIG_DECRYPTION_KEYS_VAULT_KV_VERSION', allVars.get('REMOTE_CONFIG_DECRYPTION_KEYS_VAULT_KV_VERSION'))
Updated

2022-05-13 14:44 UTC, pwnage101 approved these changes

2022-05-13 15:03 UTC, merged